const CHAPTER_COUNT=12;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const progressKey=n=>'zm-progress-chapter-'+n;
function getDone(n){return localStorage.getItem(progressKey(n))==='1'}
function applyPreferences(){const scale=Number(localStorage.getItem('zm-font-scale')||1);document.documentElement.style.setProperty('--reader-font',(17*scale)+'px');document.body.classList.toggle('high-contrast',localStorage.getItem('zm-contrast')==='1')}
function initControls(){let scale=Number(localStorage.getItem('zm-font-scale')||1);$('#fontButton')?.addEventListener('click',()=>{scale=scale>=1.18?.92:Math.round((scale+.08)*100)/100;localStorage.setItem('zm-font-scale',scale);document.documentElement.style.setProperty('--reader-font',(17*scale)+'px')});$('#contrastButton')?.addEventListener('click',()=>{document.body.classList.toggle('high-contrast');localStorage.setItem('zm-contrast',document.body.classList.contains('high-contrast')?'1':'0')})}
function refreshProgress(){let done=0;$$('[data-chapter-card]').forEach(card=>{const n=Number(card.dataset.chapterCard);const completed=getDone(n);card.classList.toggle('is-complete',completed);card.querySelector('.chapter-state')?.remove();const state=document.createElement('span');state.className='chapter-state';state.textContent=completed?'Dokončené':'Otvorené';card.appendChild(state);if(completed)done++});const pct=Math.round(done/CHAPTER_COUNT*100);if($('#progressText'))$('#progressText').textContent=`${done} z ${CHAPTER_COUNT} kapitol`;if($('#progressFill'))$('#progressFill').style.width=pct+'%';const next=[...Array(CHAPTER_COUNT)].findIndex((_,i)=>!getDone(i+1))+1;const link=$('#continueReading');if(link){if(next>0){link.href=`./chapter-${String(next).padStart(2,'0')}.html`;link.textContent=done?'Pokračovať v kapitole '+String(next).padStart(2,'0'):'Začať prvou kapitolou'}else{link.href='./zaver.html';link.textContent='Prejsť k záveru'}}}
let searchIndex=null;async function loadSearchIndex(){if(searchIndex)return searchIndex;const cards=$$('[data-chapter-card]');searchIndex=await Promise.all(cards.map(async card=>{const href=card.getAttribute('href');const html=await fetch(href,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(href);return r.text()});const doc=new DOMParser().parseFromString(html,'text/html');const article=doc.querySelector('article')||doc.querySelector('main');return{href,title:card.querySelector('.resource-text')?.textContent.trim()||href,phase:card.dataset.phase||'',text:(article?.textContent||'').replace(/\s+/g,' ').trim()}}));return searchIndex}
function excerpt(text,q){const lower=text.toLocaleLowerCase('sk');const i=lower.indexOf(q);if(i<0)return text.slice(0,180)+'…';return (i>70?'…':'')+text.slice(Math.max(0,i-70),i+q.length+110)+(i+q.length+110<text.length?'…':'')}
function initSearch(){const dlg=$('#searchDialog'),input=$('#searchInput'),results=$('#searchResults');if(!dlg||!input||!results)return;const open=async()=>{if(!dlg.open)dlg.showModal();input.focus();results.innerHTML='<p>Pripravujem vyhľadávanie…</p>';try{await loadSearchIndex();results.innerHTML='<p>Zadajte aspoň dve písmená.</p>'}catch{results.innerHTML='<p>Vyhľadávanie sa nepodarilo načítať. Kapitoly sú dostupné cez obsah.</p>'}};$('#searchButton')?.addEventListener('click',open);$('#closeSearch')?.addEventListener('click',()=>dlg.close());dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'&&dlg.open)dlg.close()});input.addEventListener('input',async()=>{const q=input.value.toLocaleLowerCase('sk').trim();if(q.length<2){results.innerHTML='<p>Zadajte aspoň dve písmená.</p>';return}const data=await loadSearchIndex();const hits=data.filter(x=>(x.title+' '+x.phase+' '+x.text).toLocaleLowerCase('sk').includes(q)).slice(0,12);results.innerHTML=hits.map(x=>`<a class="search-result" href="${x.href}"><strong>${x.title}</strong><small>${x.phase}</small><span>${excerpt(x.text,q)}</span></a>`).join('')||'<p>Nenašli sa výsledky.</p>'});if(new URLSearchParams(location.search).get('search')==='1')open()}
applyPreferences();document.addEventListener('DOMContentLoaded',()=>{initControls();refreshProgress();initSearch()});